#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

module Zipkin
  class Moments
    include ::Thrift::Struct, ::Thrift::Struct_Union
    M0 = 1
    M1 = 2
    M2 = 3
    M3 = 4
    M4 = 5

    FIELDS = {
      M0 => {:type => ::Thrift::Types::I64, :name => 'm0'},
      M1 => {:type => ::Thrift::Types::DOUBLE, :name => 'm1'},
      M2 => {:type => ::Thrift::Types::DOUBLE, :name => 'm2'},
      M3 => {:type => ::Thrift::Types::DOUBLE, :name => 'm3'},
      M4 => {:type => ::Thrift::Types::DOUBLE, :name => 'm4'}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class DependencyLink
    include ::Thrift::Struct, ::Thrift::Struct_Union
    PARENT = 1
    CHILD = 2
    DURATION_MOMENTS = 3

    FIELDS = {
      PARENT => {:type => ::Thrift::Types::STRING, :name => 'parent'},
      CHILD => {:type => ::Thrift::Types::STRING, :name => 'child'},
      DURATION_MOMENTS => {:type => ::Thrift::Types::STRUCT, :name => 'duration_moments', :class => ::Zipkin::Moments}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

  class Dependencies
    include ::Thrift::Struct, ::Thrift::Struct_Union
    START_TIME = 1
    END_TIME = 2
    LINKS = 3

    FIELDS = {
      START_TIME => {:type => ::Thrift::Types::I64, :name => 'start_time'},
      END_TIME => {:type => ::Thrift::Types::I64, :name => 'end_time'},
      LINKS => {:type => ::Thrift::Types::LIST, :name => 'links', :element => {:type => ::Thrift::Types::STRUCT, :class => ::Zipkin::DependencyLink}}
    }

    def struct_fields; FIELDS; end

    def validate
    end

    ::Thrift::Struct.generate_accessors self
  end

end
