#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'zipkin_query/zipkin_core_types'

module Zipkin
  CLIENT_SEND = %q"cs"

  CLIENT_RECV = %q"cr"

  SERVER_SEND = %q"ss"

  SERVER_RECV = %q"sr"

end
